# Generated by Django 2.2.16 on 2023-01-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="pub_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="pub_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата создания"
            ),
        ),
    ]
